---
peers:
    - peer: {host: node1, port: 3015, pubkey: "pp$HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X"}
    - peer: {host: node2, port: 3015, pubkey: "pp$28uQUgsPcsy7TQwnRxhF8GMKU4ykFLKsgf4TwDwPMNaSCXwWV8"}

http:
    external:
        peer_address: http://node3:3013/
    internal:
        listen_address: 0.0.0.0

websocket:
    internal:
        listen_address: 0.0.0.0

keys:
    password: "top secret"
    dir: ./keys

chain:
    persist: true

mining:
    autostart: true
    cuckoo:
        miner:
            executable: mean16s-generic
            extra_args: ""
            node_bits: 16
